name: PR Checks

on:
    pull_request:

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
             - name: Checkout repository
               uses: actions/checkout@v4

             - name: Install just
               run: |
                  mkdir -p "$HOME/.local/bin"
                  curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to "$HOME/.local/bin"
                  echo "$HOME/.local/bin" >> $GITHUB_PATH

             - name: "Set up Go"
               uses: actions/setup-go@v5
               with:
                  go-version: '^1.13.1'

             - name: Run lint
               run: just lint